title       = "Cargo Subcommands"
related     = ["text-editors", "development-tools", "ide"]

[entry.cargo-brew]

[entry.cargo-check]

[entry.cargo-count]

[entry.cargo-do]

[entry.cargo-dot]
crates_io_id = false
repository_url = "https://github.com/maxsnew/cargo-dot"

[entry.cargo-edit]
crates_io_id = false
repository_url = "https://github.com/killercup/cargo-edit"

[entry.cargo-extras]

[entry.cargo-fmt]

[entry.cargo-graph]

[entry.cargo-info]

[entry.cargo-multi]

[entry.cargo-outdated]

[entry.cargo-script]

[entry.cargo-show]

[entry.cargo-watch]
