title       = "Testing"
related     = ["text-editors", "development-tools", "ide"]

[entry.quickcheck]

[entry.shiny]

[entry.afl-coverage]
crates_io_id = false
name = "afl"
repository_url = "https://github.com/frewsxcv/afl.rs"
